[workspace]
members = [
    "crates/relayer",
]

[workspace.package]
name = "bitcoin-da"
repository = "https://github.com/KasarLabs/bitcoin-da"
edition = "2021"

[workspace.dependencies]
bitcoin = "0.30.1"
bitcoincore-rpc = "0.17.0"
